---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: mysql
  namespace: confluent
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    database.hostname: "mysql"
    database.port: "3306"
    database.user: ${file:/mnt/secrets/mysql-credential/sqlcreds.txt:mysql_username}
    database.password: ${file:/mnt/secrets/mysql-credential/sqlcreds.txt:mysql_password}
    database.server.id: "223344"
    database.server.name: "cloudbed"
    database.whitelist: "inventory"
    database.history.kafka.bootstrap.servers: "kafka:9071"
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    database.history.kafka.topic: "schema-changes.inventory"